In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [ ]:
def feature_catagory(data):
    numerical_feature=data.columns[data.dtypes!='object']
    catagoric_feature=data.columns[data.dtypes=='object']
    
    return numerical_feature,catagoric_feature

In [ ]:
data=pd.read_csv('./train.csv')
data.drop('id',axis=1,inplace=True)
target=data['target']
data.drop('target',axis=1,inplace=True)
data=data.drop(['Age','Departure Delay in Minutes', 'Arrival Delay in Minutes','Departure/Arrival time convenient','Flight Distance','Gate location'],axis=1)

In [ ]:
test=pd.read_csv('./test.csv')
test.drop('id',axis=1,inplace=True)
test=test.drop(['Age','Departure Delay in Minutes', 'Arrival Delay in Minutes','Departure/Arrival time convenient','Flight Distance','Gate location'],axis=1)

In [ ]:
numerical_feature,catagorical_feature = feature_catagory(data)

In [ ]:
data['target'] = target

In [ ]:
data[data['Food and drink']==0]['Food and drink'] = 5

In [ ]:
data

      Gender      Customer Type  ... Online boarding target
0     Female  disloyal Customer  ...               4      0
1     Female     Loyal Customer  ...               2      0
2       Male     Loyal Customer  ...               3      1
3     Female  disloyal Customer  ...               3      0
4     Female     Loyal Customer  ...               5      1
...      ...                ...  ...             ...    ...
2995    Male     Loyal Customer  ...               4      0
2996  Female  disloyal Customer  ...               5      0
2997  Female  disloyal Customer  ...               4      0
2998  Female  disloyal Customer  ...               4      0
2999  Female     Loyal Customer  ...               3      0

[3000 rows x 17 columns]

In [ ]:
mean = data[numerical_feature].mean()
std = data[numerical_feature].std()

data[numerical_feature] -= mean
data[numerical_feature] /=std

test[numerical_feature] -= mean
test[numerical_feature] /=std

In [ ]:
data = pd.get_dummies(data,columns = ['Gender', 'Customer Type', 'Type of Travel', 'Class','Food and drink','Leg room service'])
test = pd.get_dummies(test,columns = ['Gender', 'Customer Type', 'Type of Travel', 'Class','Food and drink','Leg room service'])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3,random_state=0)

In [ ]:
def accuracy(true, pred):   
    score = np.mean(true==pred)
    return score

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
GB=GradientBoostingClassifier()
XGB = XGBClassifier()
CAT = CatBoostClassifier(silent = True)
LGBM=LGBMClassifier()
XT=ExtraTreesClassifier()

In [ ]:
GB.fit(data,target)
XGB.fit(data,target)
CAT.fit(data,target)
LGBM.fit(data,target)
XT.fit(data,target)

ExtraTreesClassifier()

In [ ]:
y_pred1 = GB.predict(test)
y_pred2 = XGB.predict(test)
y_pred3 = CAT.predict(test)
y_pred4 = LGBM.predict(test)
y_pred5 = XT.predict(test)

In [ ]:
y=(y_pred1 + y_pred2 + y_pred3+ y_pred4+ y_pred5)

In [ ]:
y[y < 2.5] = 0
y[y > 2.5] = 1

In [ ]:
z=pd.read_csv('./sample_submission.csv')
z=z.set_index('id')
z['target']= y

In [ ]:
z.to_csv('./dummy5 + softvoting.csv')

In [ ]:
data['target'] = target

In [ ]:
data

,Gender,Customer Type,Type of Travel,Class,Seat comfort,Food and drink,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,target
0,Female,disloyal Customer,Business travel,Eco,3,3,4,3,4,4,5,4,4,4,5,4,0
1,Female,Loyal Customer,Business travel,Business,2,4,1,4,3,5,5,4,2,1,5,2,0
2,Male,Loyal Customer,Business travel,Business,1,1,4,5,5,4,4,4,4,5,4,3,1
3,Female,disloyal Customer,Business travel,Eco,3,3,3,3,3,3,2,4,5,3,4,3,0
4,Female,Loyal Customer,Business travel,Business,3,3,4,4,5,4,4,4,4,4,4,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Male,Loyal Customer,Personal Travel,Eco,1,1,1,4,4,1,3,5,3,4,2,4,0
2996,Female,disloyal Customer,Business travel,Eco,2,3,5,3,5,5,2,2,4,1,3,5,0
2997,Female,disloyal Customer,Business travel,Eco,2,2,4,2,4,4,3,2,3,4,3,4,0
2998,Female,disloyal Customer,Business travel,Business,2,2,4,2,4,4,5,2,5,5,5,4,0
2999,Female,Loyal Customer,Business travel,Eco,1,2,3,3,4,1,1,1,1,3,1,3,0

!pip install catboost
!pip install pycaret
!pip install scikit-learn==0.23.2

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from catboost import CatBoostClassifier
from pycaret.classification import *
from sklearn.model_selection import cross_val_score

In [ ]:
data=pd.read_csv('./train.csv')
data.drop('id',axis=1,inplace=True)
test=pd.read_csv('./test.csv')
test.drop('id',axis=1,inplace=True)

model_rank=pd.DataFrame(columns=['model_name','cv_accuracy_score'])

In [ ]:
model_rank.loc[len(model_rank)] = [1,2]
model_rank

  model_name cv_accuracy_score
0          1                 2
1          1                 2

clf=setup(data=data, target = 'target',session_id=1,log_experiment = True)

best = compare_models(n_select= 2, fold = 3,
                        cross_validation=True,
                        sort='Accuracy')
blender = blend_models(best)

print(cross_val_score(blender,data.iloc[:,:-1],data['target'], cv=2))

blender.score(data.iloc[:,:-1],data['target'])

In [ ]:
#모델 이름 입력으로 넣을 수 있게 하자 !
def model_best_test(n_select,fold,data,name=''):
  model_name =  f"{n_select} soft + {fold} +{name}"

  clf=setup(data=data, target = 'target',session_id=1,log_experiment = True)
  
  # 교차검증으로 가장 좋은 모델 찾기
  best = compare_models(n_select= n_select, fold = fold,
                        cross_validation=True,
                        sort='Accuracy')
  
  # n_select개 모델 soft voting 하기
  blend_4_soft = blend_models(estimator_list=best,method='soft',choose_better=True,verbose=True,fold=fold)

  tuned_top3 = [tune_model(i) for i in best]
  blender = blend_models(tuned_top3)
  stacker = stack_models(tuned_top3)
  best_auc_model = automl(optimize = 'AUC')
  
  final_model = finalize_model(best_auc_model)
  prediction = predict_model(final_model, data=test)

  #교차 검증은 어떻게..?
  
  #cv_score =cross_val_score(final_model,data.iloc[:,:-1],data['target'], cv=fold)
  #model_rank.loc[len(model_rank)] = [model_name,cv_score]
  #prediction = final_model.predict()

  return model_name, prediction

In [ ]:
class MyError(Exception):
  pass
  
def trans_pre2z(model_name,prediction,z):
    cnt=0
    for k in range(0,2000):
      if z['target'].iloc[k] == prediction['Label'].iloc[k]:
        cnt+=1
    
    #맞으면 저장
    if cnt == 2000:
      filename = f'{model_name}'
      z.to_csv('./' + filename + '.csv')  
    
    #아니면 에러처리
    if cnt!=2000:
      raise MyError()

In [ ]:
def Pred2File(model_name,prediction):
  z=pd.read_csv('./sample_submission.csv')
  z=z.set_index('id')
  z['target']= prediction['Label']

  #옮기기
  for i in range(1999,1,-1):
    z['target'].iloc[i] = z['target'].iloc[i-1]
  
  z['target'].iloc[0] =1
  z['target'].iloc[1] =0
  try:
    trans_pre2z(model_name,prediction,z)
  except MyError:
    print('제대로 옮겨지지 않았습니다.')

In [ ]:
#데이터 정제 x, 
name,pred=model_best_test(3,10)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9476  0.9864  0.9569  0.9487  0.9528  0.8940  0.8940
1       0.9619  0.9883  0.9829  0.9504  0.9664  0.9225  0.9232
2       0.9333  0.9788  0.9316  0.9478  0.9397  0.8652  0.8654
3       0.9429  0.9800  0.9316  0.9646  0.9478  0.8847  0.8854
4       0.9381  0.9774  0.9487  0.9407  0.9447  0.8744  0.8745
5       0.9333  0.9835  0.9402  0.9402  0.9402  0.8649  0.8649
6       0.9333  0.9792  0.9658  0.9187  0.9417  0.8640  0.8655
7       0.9333  0.9741  0.9060  0.9725  0.9381  0.8661  0.8686
8       0.9238  0.9740  0.9316  0.9316  0.9316  0.8456  0.8456
9       0.9426  0.9627  0.9397  0.9561  0.9478  0.8840  0.8842
Mean    0.9390  0.9784  0.9435  0.9471  0.9451  0.8765  0.8771
SD      0.0099  0.0069  0.0203  0.0148  0.0091  0.0201  0.0200

In [ ]:
Pred2File(name,pred)

In [ ]:
#리더보드가 가능은 했네 ..
df=get_leaderboard()

In [ ]:
data_org = data.copy()

In [ ]:
data_org

      Gender      Customer Type  ...  Arrival Delay in Minutes target
0     Female  disloyal Customer  ...                       0.0      0
1     Female     Loyal Customer  ...                      18.0      0
2       Male     Loyal Customer  ...                       0.0      1
3     Female  disloyal Customer  ...                       2.0      0
4     Female     Loyal Customer  ...                       0.0      1
...      ...                ...  ...                       ...    ...
2995    Male     Loyal Customer  ...                     225.0      0
2996  Female  disloyal Customer  ...                      13.0      0
2997  Female  disloyal Customer  ...                      67.0      0
2998  Female  disloyal Customer  ...                       3.0      0
2999  Female     Loyal Customer  ...                       6.0      0

[3000 rows x 23 columns]

In [ ]:
data[data['Seat comfort']==0] = 5
data[data['Departure/Arrival time convenient']==0] = 3
data[data['Food and drink']==0] = 5
data[data['Inflight wifi service']==0] = 0
data[data['Inflight entertainment']==0] = 4
data[data['Ease of Online booking']==0] = 1
data[data['Leg room service']==0] = 5
data[data['Online boarding']==0]=1

In [ ]:
#0 처리만 해줬음
name,pred=model_best_test(4,10,data[1:],'preprocessing-4')
Pred2File(name,pred)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9381  0.9887  0.9660  0.9384  0.9380  0.8901  0.8905
1       0.9143  0.9637  0.9534  0.9143  0.9143  0.8491  0.8491
2       0.9238  0.9744  0.9585  0.9238  0.9238  0.8659  0.8659
3       0.9524  0.9829  0.9752  0.9542  0.9524  0.9165  0.9178
4       0.9333  0.9851  0.9641  0.9336  0.9334  0.8828  0.8829
5       0.9238  0.9777  0.9585  0.9238  0.9238  0.8659  0.8659
6       0.9381  0.9882  0.9669  0.9386  0.9381  0.8912  0.8915
7       0.9571  0.9886  0.9769  0.9572  0.9572  0.9246  0.9246
8       0.9333  0.9714  0.9637  0.9333  0.9333  0.8827  0.8827
9       0.9282  0.9812  0.9613  0.9283  0.9283  0.8729  0.8729
Mean    0.9343  0.9802  0.9645  0.9346  0.9343  0.8842  0.8844
SD      0.0124  0.0079  0.0069  0.0127  0.0124  0.0219  0.0221

In [ ]:
#log값 취하는게 낫겠다 크기가 중요하진 않으니까.
data['Arrival Delay in Minutes']=np.log1p(data['Arrival Delay in Minutes'])

In [ ]:
data=data.drop(['Departure Delay in Minutes','Departure/Arrival time convenient','Flight Distance','Gate location'],axis=1)
test

In [ ]:
#필요 없는거 제거 
name,pred=model_best_test(4,10,data[1:],'columns + 0 + log')
Pred2File(name,pred)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9381  0.9868  0.9660  0.9384  0.9380  0.8901  0.8905
1       0.8905  0.9655  0.9413  0.8918  0.8906  0.8077  0.8085
2       0.9143  0.9683  0.9541  0.9152  0.9144  0.8495  0.8500
3       0.9381  0.9845  0.9673  0.9394  0.9382  0.8913  0.8922
4       0.9286  0.9842  0.9621  0.9299  0.9287  0.8746  0.8755
5       0.9143  0.9734  0.9534  0.9143  0.9143  0.8491  0.8491
6       0.9333  0.9901  0.9645  0.9342  0.9334  0.8829  0.8835
7       0.9429  0.9843  0.9689  0.9429  0.9429  0.8994  0.8994
8       0.9286  0.9741  0.9610  0.9286  0.9285  0.8742  0.8742
9       0.8947  0.9712  0.9430  0.8947  0.8947  0.8135  0.8135
Mean    0.9223  0.9783  0.9581  0.9229  0.9224  0.8632  0.8636
SD      0.0174  0.0082  0.0094  0.0174  0.0174  0.0307  0.0307

In [ ]:
#필요 없는거 제거 
name,pred=model_best_test(3,10,data[1:],'columns + 0 + log')
Pred2File(name,pred)

In [ ]:
data=pd.get_dummies(data,columns = ['Seat comfort', 'Food and drink', 'Inflight wifi service',
       'Inflight entertainment', 'Online support', 'Ease of Online booking',
       'On-board service', 'Leg room service', 'Baggage handling',
       'Checkin service', 'Cleanliness', 'Online boarding'])

test = pd.get_dummies(test,columns = ['Seat comfort', 'Food and drink', 'Inflight wifi service',
       'Inflight entertainment', 'Online support', 'Ease of Online booking',
       'On-board service', 'Leg room service', 'Baggage handling',
       'Checkin service', 'Cleanliness', 'Online boarding'])

In [ ]:
test

      Gender      Customer Type  ...  Online boarding_4 Online boarding_5
0     Female     Loyal Customer  ...                  0                 0
1     Female  disloyal Customer  ...                  0                 0
2     Female     Loyal Customer  ...                  0                 0
3       Male     Loyal Customer  ...                  0                 0
4     Female     Loyal Customer  ...                  1                 0
...      ...                ...  ...                ...               ...
1995  Female     Loyal Customer  ...                  0                 0
1996  Female     Loyal Customer  ...                  0                 0
1997    Male     Loyal Customer  ...                  0                 0
1998  Female     Loyal Customer  ...                  0                 0
1999  Female     Loyal Customer  ...                  0                 0

[2000 rows x 71 columns]

In [ ]:
data=data_org
test=test.drop(['Departure Delay in Minutes','Departure/Arrival time convenient','Flight Distance','Gate location'],axis=1)

data=data.drop(['Departure Delay in Minutes','Departure/Arrival time convenient','Flight Distance','Gate location'],axis=1)
#log값 취하는게 낫겠다 크기가 중요하진 않으니까.
data['Arrival Delay in Minutes']=np.log1p(data['Arrival Delay in Minutes'])
test['Arrival Delay in Minutes']=np.log1p(test['Arrival Delay in Minutes'])

In [ ]:
test['Baggage handling_0'] = 0
test['Cleanliness_0'] = 0
test['Checkin service_0'] = 0
test['On-board service_0'] = 0
test['Ease of Online booking_0'] = 0
test['Online support_0'] = 0
test['Online boarding_0'] =0

In [ ]:
test

      Gender      Customer Type  ...  Online boarding_5 Baggage handling_0
0     Female     Loyal Customer  ...                  0                  0
1     Female  disloyal Customer  ...                  0                  0
2     Female     Loyal Customer  ...                  0                  0
3       Male     Loyal Customer  ...                  0                  0
4     Female     Loyal Customer  ...                  0                  0
...      ...                ...  ...                ...                ...
1995  Female     Loyal Customer  ...                  0                  0
1996  Female     Loyal Customer  ...                  0                  0
1997    Male     Loyal Customer  ...                  0                  0
1998  Female     Loyal Customer  ...                  0                  0
1999  Female     Loyal Customer  ...                  0                  0

[2000 rows x 72 columns]

In [ ]:
name,pred =model_best_test(4,10,data,'dummy + columns + log')
Pred2File(name,pred)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9333  0.9822  0.9655  0.9180  0.9412  0.8644  0.8658
1       0.9286  0.9869  0.9573  0.9180  0.9372  0.8544  0.8555
2       0.9238  0.9803  0.9145  0.9469  0.9304  0.8463  0.8469
3       0.9476  0.9808  0.9487  0.9569  0.9528  0.8940  0.8940
4       0.9333  0.9750  0.9316  0.9478  0.9397  0.8652  0.8654
5       0.9476  0.9808  0.9573  0.9492  0.9532  0.8937  0.8938
6       0.9238  0.9834  0.9573  0.9106  0.9333  0.8446  0.8460
7       0.9286  0.9845  0.9145  0.9554  0.9345  0.8560  0.8570
8       0.9286  0.9730  0.9231  0.9474  0.9351  0.8557  0.8561
9       0.9234  0.9630  0.9138  0.9464  0.9298  0.8457  0.8463
Mean    0.9319  0.9790  0.9384  0.9397  0.9387  0.8620  0.8627
SD      0.0086  0.0066  0.0198  0.0162  0.0079  0.0173  0.0170

In [ ]:
name,pred =model_best_test(3,10,data,'dummy + columns + log')
Pred2File(name,pred)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9333  0.9824  0.9655  0.9180  0.9412  0.8644  0.8658
1       0.9333  0.9867  0.9573  0.9256  0.9412  0.8643  0.8650
2       0.9238  0.9802  0.9145  0.9469  0.9304  0.8463  0.8469
3       0.9476  0.9803  0.9487  0.9569  0.9528  0.8940  0.8940
4       0.9333  0.9754  0.9316  0.9478  0.9397  0.8652  0.8654
5       0.9476  0.9804  0.9487  0.9569  0.9528  0.8940  0.8940
6       0.9238  0.9838  0.9573  0.9106  0.9333  0.8446  0.8460
7       0.9286  0.9853  0.9145  0.9554  0.9345  0.8560  0.8570
8       0.9286  0.9722  0.9231  0.9474  0.9351  0.8557  0.8561
9       0.9234  0.9625  0.9138  0.9464  0.9298  0.8457  0.8463
Mean    0.9323  0.9789  0.9375  0.9412  0.9391  0.8630  0.8637
SD      0.0085  0.0069  0.0192  0.0160  0.0078  0.0172  0.0169

In [ ]:
#필요 없는거 제거 
name,pred=model_best_test(4,10,data[1:],'columns + log')
Pred2File(name,pred)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9333  0.9842  0.9649  0.9167  0.9402  0.8650  0.8665
1       0.9048  0.9578  0.8947  0.9273  0.9107  0.8087  0.8093
2       0.9000  0.9633  0.9035  0.9115  0.9075  0.7987  0.7987
3       0.9286  0.9812  0.8947  0.9714  0.9315  0.8571  0.8603
4       0.9333  0.9821  0.9211  0.9545  0.9375  0.8661  0.8668
5       0.9048  0.9616  0.9298  0.8983  0.9138  0.8075  0.8081
6       0.9238  0.9739  0.8957  0.9626  0.9279  0.8473  0.8498
7       0.9476  0.9816  0.9478  0.9561  0.9520  0.8944  0.8944
8       0.9143  0.9696  0.9304  0.9145  0.9224  0.8267  0.8268
9       0.9043  0.9647  0.9211  0.9052  0.9130  0.8067  0.8068
Mean    0.9195  0.9720  0.9204  0.9318  0.9257  0.8378  0.8388
SD      0.0153  0.0094  0.0227  0.0253  0.0140  0.0310  0.0313

In [ ]:

#필요 없는거 제거 
name,pred=model_best_test(3,10,data[1:],'columns + log')
Pred2File(name,pred)

NameError: ignored

In [ ]:
data=data.drop(['Departure Delay in Minutes','Departure/Arrival time convenient','Flight Distance','Gate location'],axis=1)

In [ ]:
name,pred=model_best_test(4,10,data[1:],'preprocessing-4')
Pred2File(name,pred)

IndexingError: ignored

In [ ]:
#0부터 5 전처리한거 수치형으로 바꾼 데이터
name,pred=model_best_test(3,10)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9476  0.9864  0.9569  0.9487  0.9528  0.8940  0.8940
1       0.9619  0.9883  0.9829  0.9504  0.9664  0.9225  0.9232
2       0.9333  0.9788  0.9316  0.9478  0.9397  0.8652  0.8654
3       0.9429  0.9800  0.9316  0.9646  0.9478  0.8847  0.8854
4       0.9381  0.9774  0.9487  0.9407  0.9447  0.8744  0.8745
5       0.9333  0.9835  0.9402  0.9402  0.9402  0.8649  0.8649
6       0.9333  0.9792  0.9658  0.9187  0.9417  0.8640  0.8655
7       0.9333  0.9741  0.9060  0.9725  0.9381  0.8661  0.8686
8       0.9238  0.9740  0.9316  0.9316  0.9316  0.8456  0.8456
9       0.9426  0.9627  0.9397  0.9561  0.9478  0.8840  0.8842
Mean    0.9390  0.9784  0.9435  0.9471  0.9451  0.8765  0.8771
SD      0.0099  0.0069  0.0203  0.0148  0.0091  0.0201  0.0200

NameError: ignored

In [ ]:
model_best_test(3,10)
model_best_test(4,10)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9524  0.9862  0.9655  0.9492  0.9573  0.9035  0.9037
1       0.9571  0.9885  0.9829  0.9426  0.9623  0.9127  0.9137
2       0.9333  0.9784  0.9316  0.9478  0.9397  0.8652  0.8654
3       0.9381  0.9800  0.9316  0.9561  0.9437  0.8750  0.8753
4       0.9381  0.9778  0.9487  0.9407  0.9447  0.8744  0.8745
5       0.9381  0.9825  0.9487  0.9407  0.9447  0.8744  0.8745
6       0.9286  0.9778  0.9573  0.9180  0.9372  0.8544  0.8555
7       0.9333  0.9732  0.9145  0.9640  0.9386  0.8658  0.8672
8       0.9238  0.9735  0.9231  0.9391  0.9310  0.8459  0.8461
9       0.9330  0.9617  0.9310  0.9474  0.9391  0.8647  0.8648
Mean    0.9376  0.9780  0.9435  0.9446  0.9438  0.8736  0.8741
SD      0.0096  0.0072  0.0199  0.0115  0.0089  0.0194  0.0195

In [ ]:
clf=setup(data=data, target = 'target',session_id=1)

mlp=create_model('mlp')

  # 교차검증으로 가장 좋은 모델 찾기
best = compare_models(n_select= 3, fold = 3,
                        cross_validation=True,
                        sort='Accuracy')
tuned_top3 = [tune_model(i) for i in best]

blend_models(estimator_list=tuned_top3,method='soft',choose_better=True,verbose=True,fold=3)

KeyboardInterrupt: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
get_logs()

                              run_id  ...                      tags.mlflow.log-model.history
0   b85f86682263418da345937f6f97b8a1  ...  [{"run_id": "b85f86682263418da345937f6f97b8a1"...
1   251be87d62544df9bf420ecda90dbae5  ...  [{"run_id": "251be87d62544df9bf420ecda90dbae5"...
2   709c0274b62046e5b4ebbc1a9271c212  ...  [{"run_id": "709c0274b62046e5b4ebbc1a9271c212"...
3   c87779dbc6314803bce33cf4bf5a271c  ...  [{"run_id": "c87779dbc6314803bce33cf4bf5a271c"...
4   d3cc67844cf1464699b09d371648edc5  ...  [{"run_id": "d3cc67844cf1464699b09d371648edc5"...
5   b7559103604b46e69085b8e0306ca024  ...  [{"run_id": "b7559103604b46e69085b8e0306ca024"...
6   939ebfb8e7c64d07ba62d04125796c6e  ...  [{"run_id": "939ebfb8e7c64d07ba62d04125796c6e"...
7   9f23a83e23574d48b0c972d07726a446  ...  [{"run_id": "9f23a83e23574d48b0c972d07726a446"...
8   3c6a6b5b3baa44bdb8ae6d2e0cabd820  ...  [{"run_id": "3c6a6b5b3baa44bdb8ae6d2e0cabd820"...
9   9b6ff309d75546f689fb85b2f579aebb  ...  [{"run_id": "9b6ff309d75546f689fb85b2f579aebb"...
10  3265c5c2a9504b57a2bf0cf8cb198150  ...  [{"run_id": "3265c5c2a9504b57a2bf0cf8cb198150"...
11  42e4b82be892450385c36620d3b3def2  ...  [{"run_id": "42e4b82be892450385c36620d3b3def2"...
12  b59f8c4c352c4ba185cac9cc0f1c2f52  ...  [{"run_id": "b59f8c4c352c4ba185cac9cc0f1c2f52"...
13  2dde1cdc338346e09befb9e976e6b5aa  ...  [{"run_id": "2dde1cdc338346e09befb9e976e6b5aa"...
14  279e96cc3cd34348bb54df452d2fe502  ...  [{"run_id": "279e96cc3cd34348bb54df452d2fe502"...
15  233188be66e44f29b98bdd0f32090fcc  ...  [{"run_id": "233188be66e44f29b98bdd0f32090fcc"...
16  6975e45111ea4f42ae4f10ac99f2f4df  ...                                               None

[17 rows x 242 columns]

In [ ]:
blend_models(estimator_list=best,method='soft',choose_better=True,verbose=True,fold=3)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9357  0.9875  0.9486  0.9365  0.9425  0.8696  0.8697
1       0.9271  0.9810  0.9538  0.9185  0.9358  0.8516  0.8524
2       0.9256  0.9794  0.9280  0.9377  0.9328  0.8495  0.8495
Mean    0.9295  0.9827  0.9435  0.9309  0.9371  0.8569  0.8572
SD      0.0044  0.0035  0.0111  0.0088  0.0041  0.0090  0.0089

catboost.core.CatBoostClassifier

In [ ]:
model_best_test(3,10)

      Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.9476  0.9895  0.9655  0.9412  0.9532  0.8938  0.8941
1       0.9571  0.9937  0.9829  0.9426  0.9623  0.9127  0.9137
2       0.9429  0.9881  0.9573  0.9412  0.9492  0.8839  0.8841
3       0.9333  0.9875  0.9402  0.9402  0.9402  0.8649  0.8649
4       0.9476  0.9810  0.9573  0.9492  0.9532  0.8937  0.8938
5       0.9619  0.9844  0.9573  0.9739  0.9655  0.9230  0.9231
6       0.9238  0.9815  0.9487  0.9174  0.9328  0.8449  0.8456
7       0.9238  0.9810  0.8974  0.9633  0.9292  0.8470  0.8494
8       0.9190  0.9843  0.9316  0.9237  0.9277  0.8358  0.8358
9       0.9282  0.9766  0.9224  0.9469  0.9345  0.8552  0.8555
Mean    0.9385  0.9848  0.9461  0.9440  0.9448  0.8755  0.8760
SD      0.0142  0.0048  0.0230  0.0157  0.0131  0.0287  0.0285

AttributeError: ignored

In [ ]:
all_models = models()

In [ ]:
get_logs()

ValueError: ignored

In [ ]:
final_blend_4_soft = finalize_model(blend_4_soft)

prediction = predict_model(final_blend_4_soft, data = test)

In [ ]:
prediction['Label']

0       1
1       0
2       1
3       1
4       1
       ..
1995    0
1996    1
1997    0
1998    1
1999    1
Name: Label, Length: 2000, dtype: int64

In [ ]:
for i in range(1999,1,-1):
  z['target'].iloc[i] = z['target'].iloc[i-1]

In [ ]:
prediction['Label']

0       1
1       0
2       1
3       1
4       1
       ..
1995    0
1996    1
1997    0
1998    1
1999    1
Name: Label, Length: 2000, dtype: int64

In [ ]:
z['target'].iloc[0] =1
z['target'].iloc[1] =0

In [ ]:
i=0
for k in range(0,2000):
  if z['target'].iloc[i] == prediction['Label'].iloc[i]:
    i+=1

print(i)

2000